yaml
services:
  - type: web
    name: AgroAi
    runtime: node
    buildCommand: npm install
    startCommand: pip install -r requirements.txt && node server.js
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
